### ISSUE TITLE
Broken Recipes

### ISSUE THREAD

**Issue by SaltSouls** [axperty/moredelight-forge#1]
For whatever reason a bunch of recipes in the mod that should be functional are just not working. Can't really say exactly what is causing them to not load, but a majority of the mods recipes are not working properly.

Log: [latest.log](https://gist.github.com/SaltSouls/885cb6b8171ee2ca73e9b618203f2808)

**Comment by axperty** [comment]
Hi SaltSouls,

I'll take a further look to see what's causing this issue.

Thanks for reporting this.

Have a good day,
Axperty.

**Comment by axperty** [comment]
Hi SaltSouls,

I tested the More Delight recipes in the Forge version of the game, and everything seems to work as normal. However, after taking a look at the [latest.log](https://gist.github.com/SaltSouls/885cb6b8171ee2ca73e9b618203f2808) file, seems like the issue is being cause by KubeJS. I also checked the recipe files and I couldn't find anything that could cause this error.

Could you please try to disable KubeJS and see if the problem persists? Please let me know.

Have a good day,
Axperty.

**Comment by SaltSouls** [comment]
So it seems it is a Kubejs related issue. I'll have to report this problem to them. Their system shouldn't be breaking recipes that work without the mod installed.
